# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Mapeamos el puerto 80 de la maquina virtual con el 8000 del host
  config.vm.network "forwarded_port", guest: 3000, host: 8000

  # Sincronizamos el directorio src/ del host con el directorio /srv/webserver de la maquina virtual
  config.vm.synced_folder "src/", "/srv/webserver"
  
  # Deshabilitamos la sincronizacion de la carpeta /vagrant (esta por defecto)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Utilizamos shell como provisioner para installar el paquete nodejs
  config.vm.provision "shell", inline: <<-SHELL
     yum check-update
     yum install -y epel-release nodejs
  SHELL
end
