---
- name: Instalando el paquete de epel-release
  yum:
    name: epel-release
    state: present

- name: Instalando el paquete de nodejs 
  yum:
    name: nodejs
    state: present

#- name: Copiando el archivo de server.js
#  copy:
#    src: "server.js"
#    dest: "/home/vagrant/server.js"

- name: Generando el archivo de server.js
  template:
    src: "server.js.j2"
    dest: "/home/vagrant/server.js"